import type { Meal, Sport, WeekDay, Provider, SwapAlternative } from './types';

export const BASE = { cals: 2100, p: 150, c: 225, f: 64 };

export const INITIAL_SPORTS: Sport[] = [
  { id: 'salsa', name: 'Salsa (baile)', emoji: '💃', min: 60, kcal: 360, on: false },
  { id: 'maquinas', name: 'Gimnasio: máquinas', emoji: '🏋️', min: 50, kcal: 300, on: false },
  { id: 'cardiosuave', name: 'Cardio suave (sin impacto)', emoji: '🚴', min: 20, kcal: 130, on: false },
  { id: 'basket', name: 'Baloncesto', emoji: '🏀', min: 120, kcal: 900, on: false },
  { id: 'cardiocl', name: 'Clase de cardio', emoji: '🤸', min: 45, kcal: 380, on: false },
  { id: 'core', name: 'Core / abdominales', emoji: '🧘', min: 30, kcal: 120, on: false },
  { id: 'pump', name: 'Cardio pump', emoji: '🔥', min: 45, kcal: 400, on: false },
  { id: 'walk', name: 'Caminar (descanso activo)', emoji: '🚶', min: 40, kcal: 140, on: false },
];

export const INITIAL_PROVIDERS: Provider[] = [
  { id: 'apple', name: 'Apple Health', on: false, status: 'needs_native' },
  { id: 'google', name: 'Google Fit', on: false, status: 'disconnected' },
  { id: 'strava', name: 'Strava', on: false, status: 'disconnected' },
  { id: 'fitbit', name: 'Fitbit', on: false, status: 'disconnected' },
  { id: 'garmin', name: 'Garmin Connect', on: false, status: 'coming_soon' },
  { id: 'samsung', name: 'Samsung Health', on: false, status: 'needs_native' },
];

export const MEALS: Meal[] = [
  {
    slot: 'Desayuno',
    name: 'Porridge de espelta con quark y arándanos',
    kcal: 477, p: 29, c: 66, f: 12,
    emoji: '🥣', time: '10 min', diff: 'Fácil',
    swatch: 'linear-gradient(135deg,#ffc24d,#ff6a3d)',
    ingredients: [
      { n: 'Copos de espelta', g: 70, kcal: 233, p: 8, c: 47, f: 2 },
      { n: 'Quark desnatado', g: 150, kcal: 100, p: 18, c: 6, f: 0 },
      { n: 'Arándanos', g: 80, kcal: 46, p: 1, c: 11, f: 0 },
      { n: 'Nueces', g: 15, kcal: 98, p: 2, c: 2, f: 10 },
      { n: 'Canela', g: 2, kcal: 0, p: 0, c: 0, f: 0 },
    ],
    steps: [
      'Cuece los copos de espelta con agua o bebida vegetal 5 min.',
      'Mezcla el quark fuera del fuego para no perder cremosidad.',
      'Corona con los arándanos, las nueces y la canela.',
    ],
  },
  {
    slot: 'Almuerzo',
    name: 'Lentejas con arroz integral y pimiento',
    kcal: 584, p: 24, c: 95, f: 13,
    emoji: '🍲', time: '25 min', diff: 'Media',
    swatch: 'linear-gradient(135deg,#ffb84d,#ef6f24)',
    ingredients: [
      { n: 'Lentejas cocidas', g: 200, kcal: 232, p: 18, c: 40, f: 1 },
      { n: 'Arroz integral', g: 60, kcal: 213, p: 4, c: 45, f: 2 },
      { n: 'Pimiento rojo', g: 100, kcal: 31, p: 1, c: 6, f: 0 },
      { n: 'Aceite de oliva virgen extra', g: 8, kcal: 70, p: 0, c: 0, f: 8 },
      { n: 'Cebolla', g: 50, kcal: 20, p: 1, c: 5, f: 0 },
    ],
    steps: [
      'Pocha la cebolla y el pimiento con el AOVE 5 min.',
      'Añade las lentejas cocidas y calienta 5 min.',
      'Sirve sobre el arroz integral. La vitamina C del pimiento potencia la absorción del hierro.',
    ],
  },
  {
    slot: 'Snack',
    name: 'Quark con edamame y frutos rojos',
    kcal: 236, p: 29, c: 19, f: 4,
    emoji: '🫛', time: '5 min', diff: 'Fácil',
    swatch: 'linear-gradient(135deg,#57d39a,#11a866)',
    ingredients: [
      { n: 'Quark desnatado', g: 150, kcal: 100, p: 18, c: 6, f: 0 },
      { n: 'Edamame', g: 90, kcal: 109, p: 10, c: 8, f: 4 },
      { n: 'Frutos rojos', g: 60, kcal: 27, p: 1, c: 5, f: 0 },
    ],
    steps: [
      'Cuece el edamame 4 min y sálalo ligeramente.',
      'Acompaña con el quark y los frutos rojos.',
    ],
  },
  {
    slot: 'Cena',
    name: 'Tofu salteado con boniato y brócoli',
    kcal: 501, p: 31, c: 53, f: 20,
    emoji: '🍠', time: '25 min', diff: 'Media',
    swatch: 'linear-gradient(135deg,#ff9a4d,#ff6a3d)',
    ingredients: [
      { n: 'Tofu firme', g: 200, kcal: 194, p: 24, c: 4, f: 10 },
      { n: 'Boniato', g: 200, kcal: 172, p: 3, c: 40, f: 0 },
      { n: 'Brócoli', g: 120, kcal: 41, p: 3, c: 8, f: 0 },
      { n: 'Aceite de oliva virgen extra', g: 10, kcal: 88, p: 0, c: 0, f: 10 },
      { n: 'Salsa de soja', g: 10, kcal: 6, p: 1, c: 1, f: 0 },
    ],
    steps: [
      'Asa el boniato en dados 18 min a 200°.',
      'Saltea el tofu hasta dorar y añade el brócoli al vapor.',
      'Liga con la salsa de soja y sirve. En día de descanso, reduce el boniato a la mitad.',
    ],
  },
];

export const MEAL_ALTERNATIVES: Record<string, Meal[]> = {
  'Desayuno': [
    {
      slot: 'Desayuno', name: 'Tostada de centeno con aguacate y huevo',
      kcal: 420, p: 22, c: 38, f: 18,
      emoji: '🥑', time: '8 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#a8e063,#56ab2f)',
      ingredients: [
        { n: 'Pan de centeno', g: 80, kcal: 198, p: 7, c: 38, f: 2 },
        { n: 'Aguacate', g: 80, kcal: 128, p: 2, c: 5, f: 12 },
        { n: 'Huevo', g: 60, kcal: 86, p: 7, c: 0, f: 6 },
        { n: 'Tomate cherry', g: 60, kcal: 18, p: 1, c: 3, f: 0 },
      ],
      steps: ['Tuesta el pan.', 'Aplasta el aguacate con sal y limón.', 'Fríe el huevo y coloca todo.'],
    },
    {
      slot: 'Desayuno', name: 'Gofre de avena y plátano',
      kcal: 395, p: 18, c: 62, f: 8,
      emoji: '🧇', time: '15 min', diff: 'Media',
      swatch: 'linear-gradient(135deg,#f6d365,#fda085)',
      ingredients: [
        { n: 'Copos de avena', g: 80, kcal: 304, p: 10, c: 54, f: 6 },
        { n: 'Plátano', g: 100, kcal: 89, p: 1, c: 23, f: 0 },
        { n: 'Huevo', g: 60, kcal: 86, p: 7, c: 0, f: 6 },
        { n: 'Leche de avena', g: 80, kcal: 34, p: 1, c: 6, f: 1 },
      ],
      steps: ['Tritura todos los ingredientes.', 'Cocina en gofrera 4 min.', 'Acompaña con fruta fresca.'],
    },
    {
      slot: 'Desayuno', name: 'Smoothie bowl de frutos rojos',
      kcal: 380, p: 20, c: 52, f: 9,
      emoji: '🫐', time: '5 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ffb84d,#ff8a4c)',
      ingredients: [
        { n: 'Frutos rojos congelados', g: 150, kcal: 68, p: 1, c: 15, f: 0 },
        { n: 'Skyr', g: 150, kcal: 96, p: 17, c: 6, f: 0 },
        { n: 'Granola sin azúcar', g: 40, kcal: 172, p: 4, c: 28, f: 6 },
        { n: 'Semillas de chía', g: 10, kcal: 49, p: 2, c: 4, f: 3 },
      ],
      steps: ['Tritura frutos rojos con el skyr.', 'Vierte en bol y decora con granola y chía.'],
    },
    {
      slot: 'Desayuno', name: 'Revuelto de tofu y espinacas',
      kcal: 350, p: 28, c: 12, f: 20,
      emoji: '🍳', time: '10 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#57d39a,#18bd73)',
      ingredients: [
        { n: 'Tofu firme', g: 180, kcal: 175, p: 22, c: 3, f: 9 },
        { n: 'Espinacas frescas', g: 80, kcal: 18, p: 2, c: 3, f: 0 },
        { n: 'Aceite de oliva', g: 10, kcal: 88, p: 0, c: 0, f: 10 },
        { n: 'Cúrcuma y pimienta', g: 3, kcal: 0, p: 0, c: 0, f: 0 },
      ],
      steps: ['Desmenuza el tofu y saltea con cúrcuma.', 'Añade espinacas y cuece 3 min.'],
    },
    {
      slot: 'Desayuno', name: 'Tortilla francesa con pavo',
      kcal: 380, p: 32, c: 4, f: 26,
      emoji: '🥚', time: '8 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#f6d365,#fda085)',
      ingredients: [
        { n: 'Huevo', g: 120, kcal: 173, p: 15, c: 1, f: 12 },
        { n: 'Pechuga de pavo', g: 60, kcal: 81, p: 18, c: 0, f: 1 },
        { n: 'Aceite de oliva', g: 8, kcal: 70, p: 0, c: 0, f: 8 },
        { n: 'Espárragos', g: 60, kcal: 12, p: 1, c: 2, f: 0 },
      ],
      steps: ['Saltea el pavo.', 'Añade los huevos batidos y cuaja la tortilla.'],
    },
  ],
  'Almuerzo': [
    {
      slot: 'Almuerzo', name: 'Buddha bowl de quinoa y verduras',
      kcal: 560, p: 22, c: 78, f: 16,
      emoji: '🥗', time: '20 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#43e97b,#38f9d7)',
      ingredients: [
        { n: 'Quinoa cocida', g: 180, kcal: 222, p: 8, c: 40, f: 4 },
        { n: 'Garbanzos asados', g: 100, kcal: 164, p: 9, c: 27, f: 3 },
        { n: 'Aguacate', g: 60, kcal: 96, p: 1, c: 3, f: 9 },
        { n: 'Edamame', g: 80, kcal: 97, p: 8, c: 7, f: 4 },
        { n: 'Tahini', g: 15, kcal: 89, p: 3, c: 3, f: 8 },
      ],
      steps: ['Cuece la quinoa 15 min.', 'Asa los garbanzos con especias 20 min a 200°.', 'Monta el bol y aliña con tahini.'],
    },
    {
      slot: 'Almuerzo', name: 'Curry de garbanzos con arroz',
      kcal: 580, p: 20, c: 92, f: 14,
      emoji: '🍛', time: '30 min', diff: 'Media',
      swatch: 'linear-gradient(135deg,#f7971e,#ffd200)',
      ingredients: [
        { n: 'Garbanzos cocidos', g: 200, kcal: 246, p: 14, c: 41, f: 4 },
        { n: 'Arroz basmati', g: 60, kcal: 213, p: 4, c: 46, f: 0 },
        { n: 'Leche de coco light', g: 100, kcal: 80, p: 1, c: 3, f: 8 },
        { n: 'Tomate triturado', g: 100, kcal: 24, p: 1, c: 5, f: 0 },
        { n: 'Curry en polvo', g: 5, kcal: 14, p: 1, c: 2, f: 0 },
      ],
      steps: ['Pocha cebolla y especias.', 'Añade tomate, leche de coco y garbanzos. Cuece 15 min.', 'Sirve con arroz.'],
    },
    {
      slot: 'Almuerzo', name: 'Pasta de espelta con edamame y pesto',
      kcal: 590, p: 28, c: 86, f: 14,
      emoji: '🍝', time: '20 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ff9a4d,#ff6a3d)',
      ingredients: [
        { n: 'Pasta de espelta', g: 90, kcal: 315, p: 12, c: 62, f: 2 },
        { n: 'Edamame', g: 100, kcal: 121, p: 11, c: 9, f: 5 },
        { n: 'Pesto de albahaca', g: 30, kcal: 120, p: 2, c: 2, f: 12 },
        { n: 'Levadura nutricional', g: 10, kcal: 38, p: 5, c: 4, f: 1 },
      ],
      steps: ['Cuece la pasta al dente.', 'Mezcla con edamame y pesto caliente.', 'Espolvorea levadura nutricional.'],
    },
    {
      slot: 'Almuerzo', name: 'Ensalada templada de lentejas',
      kcal: 520, p: 26, c: 68, f: 12,
      emoji: '🥙', time: '15 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ffd08a,#ff8a4c)',
      ingredients: [
        { n: 'Lentejas cocidas', g: 200, kcal: 232, p: 18, c: 40, f: 1 },
        { n: 'Patata cocida', g: 150, kcal: 129, p: 3, c: 30, f: 0 },
        { n: 'Espinacas baby', g: 60, kcal: 14, p: 2, c: 2, f: 0 },
        { n: 'Aceite de oliva', g: 15, kcal: 132, p: 0, c: 0, f: 15 },
        { n: 'Vinagre de módena', g: 10, kcal: 12, p: 0, c: 3, f: 0 },
      ],
      steps: ['Calienta lentejas y patata.', 'Mezcla sobre espinacas y aliña.'],
    },
    {
      slot: 'Almuerzo', name: 'Pechuga de pollo con arroz y verduras',
      kcal: 560, p: 48, c: 55, f: 12,
      emoji: '🍗', time: '25 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ff9a4d,#ff6a3d)',
      ingredients: [
        { n: 'Pechuga de pollo', g: 160, kcal: 264, p: 50, c: 0, f: 6 },
        { n: 'Arroz integral', g: 60, kcal: 213, p: 4, c: 45, f: 2 },
        { n: 'Brócoli', g: 120, kcal: 41, p: 3, c: 8, f: 0 },
        { n: 'Aceite de oliva', g: 8, kcal: 70, p: 0, c: 0, f: 8 },
      ],
      steps: ['Cocina el arroz.', 'Plancha el pollo 6–7 min por lado.', 'Saltea el brócoli y sirve.'],
    },
    {
      slot: 'Almuerzo', name: 'Salmón a la plancha con quinoa',
      kcal: 580, p: 42, c: 40, f: 24,
      emoji: '🐟', time: '20 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ff9a4d,#ff6a3d)',
      ingredients: [
        { n: 'Salmón', g: 150, kcal: 312, p: 34, c: 0, f: 20 },
        { n: 'Quinoa cocida', g: 150, kcal: 185, p: 7, c: 32, f: 3 },
        { n: 'Espárragos', g: 100, kcal: 20, p: 2, c: 4, f: 0 },
        { n: 'Aceite de oliva', g: 5, kcal: 44, p: 0, c: 0, f: 5 },
      ],
      steps: ['Plancha el salmón 4 min por lado.', 'Calienta la quinoa y acompaña con espárragos.'],
    },
    {
      slot: 'Almuerzo', name: 'Pavo al horno con patata',
      kcal: 540, p: 46, c: 48, f: 14,
      emoji: '🦃', time: '35 min', diff: 'Media',
      swatch: 'linear-gradient(135deg,#f7971e,#ffd200)',
      ingredients: [
        { n: 'Pechuga de pavo', g: 160, kcal: 216, p: 48, c: 0, f: 2 },
        { n: 'Patata', g: 200, kcal: 172, p: 4, c: 40, f: 0 },
        { n: 'Zanahoria', g: 80, kcal: 33, p: 1, c: 7, f: 0 },
        { n: 'Aceite de oliva', g: 10, kcal: 88, p: 0, c: 0, f: 10 },
      ],
      steps: ['Hornea pavo y patata a 200° durante 30 min.', 'Sirve con zanahoria al vapor.'],
    },
    {
      slot: 'Almuerzo', name: 'Atún con ensalada y pan integral',
      kcal: 490, p: 40, c: 38, f: 16,
      emoji: '🥗', time: '10 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#43e97b,#38f9d7)',
      ingredients: [
        { n: 'Atún al natural', g: 120, kcal: 132, p: 30, c: 0, f: 1 },
        { n: 'Lechuga y tomate', g: 150, kcal: 28, p: 2, c: 5, f: 0 },
        { n: 'Pan integral', g: 60, kcal: 150, p: 6, c: 28, f: 2 },
        { n: 'Aceite de oliva', g: 10, kcal: 88, p: 0, c: 0, f: 10 },
        { n: 'Huevo duro', g: 60, kcal: 86, p: 7, c: 0, f: 6 },
      ],
      steps: ['Escurre el atún.', 'Monta la ensalada con huevo y aliña.', 'Acompaña con pan.'],
    },
    {
      slot: 'Almuerzo', name: 'Merluza al vapor con arroz',
      kcal: 470, p: 38, c: 52, f: 8,
      emoji: '🌊', time: '25 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#57d39a,#11a866)',
      ingredients: [
        { n: 'Merluza', g: 180, kcal: 162, p: 36, c: 0, f: 2 },
        { n: 'Arroz basmati', g: 60, kcal: 213, p: 4, c: 46, f: 0 },
        { n: 'Judías verdes', g: 120, kcal: 38, p: 2, c: 7, f: 0 },
        { n: 'Aceite de oliva', g: 8, kcal: 70, p: 0, c: 0, f: 8 },
      ],
      steps: ['Cocina el arroz.', 'Vaporiza la merluza 10 min.', 'Sirve con judías verdes.'],
    },
    {
      slot: 'Almuerzo', name: 'Pollo al curry con arroz basmati',
      kcal: 590, p: 44, c: 58, f: 16,
      emoji: '🍛', time: '30 min', diff: 'Media',
      swatch: 'linear-gradient(135deg,#f7971e,#ffd200)',
      ingredients: [
        { n: 'Pechuga de pollo', g: 150, kcal: 248, p: 47, c: 0, f: 6 },
        { n: 'Arroz basmati', g: 60, kcal: 213, p: 4, c: 46, f: 0 },
        { n: 'Leche de coco light', g: 80, kcal: 64, p: 1, c: 2, f: 6 },
        { n: 'Curry en polvo', g: 5, kcal: 14, p: 1, c: 2, f: 0 },
        { n: 'Aceite de oliva', g: 5, kcal: 44, p: 0, c: 0, f: 5 },
      ],
      steps: ['Dora el pollo con curry.', 'Añade leche de coco y cuece 12 min.', 'Sirve con arroz.'],
    },
  ],
  'Snack': [
    {
      slot: 'Snack', name: 'Hummus con crudités',
      kcal: 210, p: 9, c: 22, f: 9,
      emoji: '🫘', time: '5 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#f8b500,#f05e23)',
      ingredients: [
        { n: 'Hummus', g: 80, kcal: 156, p: 7, c: 14, f: 8 },
        { n: 'Zanahoria', g: 80, kcal: 33, p: 1, c: 7, f: 0 },
        { n: 'Pepino', g: 80, kcal: 13, p: 1, c: 2, f: 0 },
        { n: 'Apio', g: 50, kcal: 8, p: 0, c: 2, f: 0 },
      ],
      steps: ['Corta las verduras en bastones.', 'Sirve con el hummus.'],
    },
    {
      slot: 'Snack', name: 'Yogur griego con nueces y miel',
      kcal: 250, p: 14, c: 18, f: 12,
      emoji: '🍯', time: '2 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ffecd2,#fcb69f)',
      ingredients: [
        { n: 'Yogur griego 0%', g: 150, kcal: 88, p: 15, c: 6, f: 0 },
        { n: 'Nueces', g: 20, kcal: 131, p: 3, c: 3, f: 13 },
        { n: 'Miel', g: 10, kcal: 30, p: 0, c: 8, f: 0 },
      ],
      steps: ['Vierte el yogur en bol.', 'Añade las nueces y riega con miel.'],
    },
    {
      slot: 'Snack', name: 'Batido de proteína vegetal',
      kcal: 220, p: 25, c: 18, f: 4,
      emoji: '🥤', time: '3 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ffb84d,#ef6f24)',
      ingredients: [
        { n: 'Proteína vegetal en polvo', g: 30, kcal: 120, p: 22, c: 4, f: 2 },
        { n: 'Bebida de avena', g: 200, kcal: 90, p: 3, c: 14, f: 3 },
        { n: 'Plátano', g: 60, kcal: 53, p: 1, c: 13, f: 0 },
      ],
      steps: ['Tritura todos los ingredientes hasta homogeneizar.'],
    },
    {
      slot: 'Snack', name: 'Manzana con crema de almendras',
      kcal: 230, p: 5, c: 28, f: 11,
      emoji: '🍎', time: '2 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#d4fc79,#96e6a1)',
      ingredients: [
        { n: 'Manzana', g: 180, kcal: 94, p: 0, c: 25, f: 0 },
        { n: 'Crema de almendras', g: 20, kcal: 122, p: 4, c: 4, f: 11 },
      ],
      steps: ['Corta la manzana en gajos.', 'Acompaña con la crema de almendras.'],
    },
  ],
  'Cena': [
    {
      slot: 'Cena', name: 'Crema de calabaza con semillas',
      kcal: 380, p: 10, c: 48, f: 16,
      emoji: '🎃', time: '25 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#f7971e,#ffd200)',
      ingredients: [
        { n: 'Calabaza', g: 300, kcal: 72, p: 2, c: 17, f: 0 },
        { n: 'Cebolla', g: 60, kcal: 24, p: 1, c: 6, f: 0 },
        { n: 'Aceite de oliva', g: 15, kcal: 132, p: 0, c: 0, f: 15 },
        { n: 'Semillas de girasol', g: 25, kcal: 148, p: 5, c: 5, f: 13 },
        { n: 'Caldo de verduras', g: 200, kcal: 10, p: 0, c: 2, f: 0 },
      ],
      steps: ['Pocha cebolla, añade calabaza y caldo. Cuece 20 min.', 'Tritura y sirve con semillas.'],
    },
    {
      slot: 'Cena', name: 'Tortilla de verduras con ensalada',
      kcal: 440, p: 28, c: 22, f: 26,
      emoji: '🥚', time: '20 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#f6d365,#fda085)',
      ingredients: [
        { n: 'Huevo', g: 180, kcal: 259, p: 22, c: 1, f: 18 },
        { n: 'Pimiento y cebolla', g: 100, kcal: 35, p: 1, c: 8, f: 0 },
        { n: 'Espinacas', g: 60, kcal: 14, p: 2, c: 2, f: 0 },
        { n: 'Aceite de oliva', g: 15, kcal: 132, p: 0, c: 0, f: 15 },
        { n: 'Lechuga y tomate', g: 120, kcal: 22, p: 1, c: 4, f: 0 },
      ],
      steps: ['Saltea verduras 5 min.', 'Añade huevos batidos y cuaja la tortilla.', 'Sirve con ensalada.'],
    },
    {
      slot: 'Cena', name: 'Sopa de lentejas rojas',
      kcal: 450, p: 24, c: 64, f: 10,
      emoji: '🥣', time: '30 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ff8a4c,#ff6a3d)',
      ingredients: [
        { n: 'Lentejas rojas', g: 100, kcal: 340, p: 22, c: 58, f: 1 },
        { n: 'Tomate triturado', g: 100, kcal: 24, p: 1, c: 5, f: 0 },
        { n: 'Caldo de verduras', g: 400, kcal: 20, p: 0, c: 4, f: 0 },
        { n: 'Aceite de oliva', g: 10, kcal: 88, p: 0, c: 0, f: 10 },
        { n: 'Comino y pimentón', g: 3, kcal: 8, p: 0, c: 1, f: 0 },
      ],
      steps: ['Sofríe especias en aceite.', 'Añade lentejas, tomate y caldo. Cuece 25 min.'],
    },
    {
      slot: 'Cena', name: 'Seitán al horno con patata y brócoli',
      kcal: 480, p: 38, c: 44, f: 14,
      emoji: '🥦', time: '35 min', diff: 'Media',
      swatch: 'linear-gradient(135deg,#11998e,#38ef7d)',
      ingredients: [
        { n: 'Seitán', g: 150, kcal: 218, p: 38, c: 8, f: 2 },
        { n: 'Patata', g: 180, kcal: 155, p: 4, c: 36, f: 0 },
        { n: 'Brócoli', g: 150, kcal: 51, p: 4, c: 10, f: 0 },
        { n: 'Aceite de oliva', g: 15, kcal: 132, p: 0, c: 0, f: 15 },
        { n: 'Romero y ajo', g: 5, kcal: 8, p: 0, c: 2, f: 0 },
      ],
      steps: ['Marina el seitán con aceite y romero.', 'Asa todo a 200° durante 30 min.'],
    },
    {
      slot: 'Cena', name: 'Salmón con brócoli',
      kcal: 520, p: 40, c: 18, f: 28,
      emoji: '🐟', time: '20 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ff9a4d,#ff6a3d)',
      ingredients: [
        { n: 'Salmón', g: 150, kcal: 312, p: 34, c: 0, f: 20 },
        { n: 'Brócoli', g: 180, kcal: 61, p: 5, c: 12, f: 0 },
        { n: 'Aceite de oliva', g: 10, kcal: 88, p: 0, c: 0, f: 10 },
        { n: 'Limón', g: 20, kcal: 6, p: 0, c: 2, f: 0 },
      ],
      steps: ['Plancha el salmón.', 'Cocina el brócoli al vapor y aliña con limón.'],
    },
    {
      slot: 'Cena', name: 'Pechuga de pollo a la plancha con ensalada',
      kcal: 450, p: 48, c: 12, f: 18,
      emoji: '🥗', time: '15 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ff9a4d,#ff6a3d)',
      ingredients: [
        { n: 'Pechuga de pollo', g: 160, kcal: 264, p: 50, c: 0, f: 6 },
        { n: 'Lechuga y tomate', g: 150, kcal: 28, p: 2, c: 5, f: 0 },
        { n: 'Aceite de oliva', g: 12, kcal: 106, p: 0, c: 0, f: 12 },
        { n: 'Vinagre', g: 10, kcal: 2, p: 0, c: 0, f: 0 },
      ],
      steps: ['Plancha el pollo.', 'Prepara la ensalada y aliña.'],
    },
    {
      slot: 'Cena', name: 'Pescado blanco con verduras al vapor',
      kcal: 420, p: 38, c: 22, f: 14,
      emoji: '🥦', time: '25 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#57d39a,#11a866)',
      ingredients: [
        { n: 'Pescado blanco', g: 180, kcal: 162, p: 36, c: 0, f: 2 },
        { n: 'Calabacín', g: 150, kcal: 26, p: 2, c: 5, f: 0 },
        { n: 'Zanahoria', g: 100, kcal: 41, p: 1, c: 10, f: 0 },
        { n: 'Aceite de oliva', g: 12, kcal: 106, p: 0, c: 0, f: 12 },
      ],
      steps: ['Vaporiza el pescado y las verduras.', 'Aliña con AOVE.'],
    },
    {
      slot: 'Cena', name: 'Pavo con boniato asado',
      kcal: 500, p: 44, c: 42, f: 12,
      emoji: '🍠', time: '30 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#ff9a4d,#ff6a3d)',
      ingredients: [
        { n: 'Pechuga de pavo', g: 150, kcal: 203, p: 45, c: 0, f: 2 },
        { n: 'Boniato', g: 200, kcal: 172, p: 3, c: 40, f: 0 },
        { n: 'Aceite de oliva', g: 10, kcal: 88, p: 0, c: 0, f: 10 },
      ],
      steps: ['Asa el boniato 25 min a 200°.', 'Plancha el pavo y sirve.'],
    },
    {
      slot: 'Cena', name: 'Huevos revueltos con espárragos',
      kcal: 380, p: 28, c: 8, f: 26,
      emoji: '🍳', time: '12 min', diff: 'Fácil',
      swatch: 'linear-gradient(135deg,#f6d365,#fda085)',
      ingredients: [
        { n: 'Huevo', g: 180, kcal: 259, p: 22, c: 1, f: 18 },
        { n: 'Espárragos', g: 120, kcal: 24, p: 3, c: 4, f: 0 },
        { n: 'Aceite de oliva', g: 10, kcal: 88, p: 0, c: 0, f: 10 },
      ],
      steps: ['Saltea los espárragos.', 'Añade los huevos y remueve hasta cuajar.'],
    },
  ],
};

export const SWAPS: Record<string, SwapAlternative[]> = {
  // Cereales y hidratos base
  'Arroz integral': [
    { n: 'Quinoa cocida', g: 70, kcal: 210, p: 10, c: 44, f: 3 },
    { n: 'Espelta en grano', g: 65, kcal: 222, p: 8, c: 46, f: 2 },
    { n: 'Boniato asado', g: 240, kcal: 206, p: 4, c: 48, f: 0 },
    { n: 'Cuscús integral', g: 60, kcal: 216, p: 7, c: 44, f: 1 },
  ],
  'Copos de espelta': [
    { n: 'Copos de avena', g: 70, kcal: 266, p: 9, c: 47, f: 5 },
    { n: 'Quinoa hinchada', g: 60, kcal: 222, p: 8, c: 39, f: 3 },
    { n: 'Muesli sin azúcar', g: 65, kcal: 243, p: 7, c: 43, f: 5 },
  ],
  'Copos de avena': [
    { n: 'Copos de espelta', g: 70, kcal: 233, p: 8, c: 47, f: 2 },
    { n: 'Quinoa hinchada', g: 60, kcal: 222, p: 8, c: 39, f: 3 },
    { n: 'Muesli sin azúcar', g: 65, kcal: 243, p: 7, c: 43, f: 5 },
    { n: 'Trigo sarraceno en grano', g: 60, kcal: 204, p: 7, c: 42, f: 1 },
  ],
  'Pan de centeno': [
    { n: 'Pan integral de espelta', g: 80, kcal: 192, p: 7, c: 36, f: 2 },
    { n: 'Tortitas de maíz', g: 50, kcal: 190, p: 4, c: 38, f: 2 },
    { n: 'Pan de avena', g: 80, kcal: 200, p: 8, c: 36, f: 4 },
    { n: 'Wasa de centeno', g: 60, kcal: 195, p: 6, c: 38, f: 2 },
  ],
  'Pasta de espelta': [
    { n: 'Pasta integral de trigo', g: 90, kcal: 310, p: 11, c: 60, f: 2 },
    { n: 'Pasta de legumbres', g: 80, kcal: 285, p: 18, c: 46, f: 3 },
    { n: 'Pasta de arroz', g: 90, kcal: 315, p: 6, c: 66, f: 1 },
    { n: 'Fideos de konjac', g: 200, kcal: 10, p: 0, c: 2, f: 0 },
  ],
  'Boniato': [
    { n: 'Patata cocida', g: 200, kcal: 172, p: 4, c: 40, f: 0 },
    { n: 'Quinoa cocida', g: 130, kcal: 168, p: 7, c: 30, f: 3 },
    { n: 'Yuca cocida', g: 160, kcal: 176, p: 1, c: 42, f: 0 },
    { n: 'Zanahoria cocida', g: 280, kcal: 118, p: 3, c: 27, f: 0 },
  ],
  'Patata cocida': [
    { n: 'Boniato asado', g: 180, kcal: 155, p: 3, c: 36, f: 0 },
    { n: 'Quinoa cocida', g: 120, kcal: 154, p: 7, c: 28, f: 3 },
    { n: 'Arroz integral', g: 60, kcal: 213, p: 4, c: 45, f: 2 },
    { n: 'Yuca cocida', g: 150, kcal: 165, p: 1, c: 40, f: 0 },
  ],
  'Quinoa cocida': [
    { n: 'Arroz integral', g: 60, kcal: 213, p: 4, c: 45, f: 2 },
    { n: 'Mijo cocido', g: 150, kcal: 180, p: 5, c: 38, f: 2 },
    { n: 'Bulgur integral', g: 80, kcal: 220, p: 7, c: 46, f: 1 },
    { n: 'Cuscús integral', g: 70, kcal: 245, p: 8, c: 50, f: 1 },
  ],
  // Proteínas vegetales
  'Tofu firme': [
    { n: 'Seitán', g: 120, kcal: 174, p: 30, c: 6, f: 2 },
    { n: 'Tempeh', g: 120, kcal: 228, p: 22, c: 10, f: 12 },
    { n: 'Garbanzos cocidos', g: 200, kcal: 246, p: 18, c: 40, f: 4 },
    { n: 'Edamame', g: 200, kcal: 242, p: 22, c: 18, f: 10 },
  ],
  'Seitán': [
    { n: 'Tofu firme', g: 150, kcal: 145, p: 18, c: 3, f: 8 },
    { n: 'Tempeh', g: 100, kcal: 190, p: 18, c: 8, f: 10 },
    { n: 'Proteína de soja texturizada', g: 60, kcal: 192, p: 30, c: 12, f: 2 },
    { n: 'Garbanzos asados', g: 180, kcal: 222, p: 16, c: 36, f: 4 },
  ],
  'Lentejas cocidas': [
    { n: 'Garbanzos cocidos', g: 200, kcal: 246, p: 18, c: 40, f: 4 },
    { n: 'Alubias blancas', g: 200, kcal: 236, p: 16, c: 42, f: 1 },
    { n: 'Tofu firme', g: 200, kcal: 194, p: 24, c: 4, f: 10 },
    { n: 'Edamame', g: 160, kcal: 194, p: 18, c: 14, f: 8 },
  ],
  'Lentejas rojas': [
    { n: 'Lentejas verdes', g: 100, kcal: 350, p: 24, c: 60, f: 1 },
    { n: 'Garbanzos cocidos', g: 220, kcal: 271, p: 20, c: 44, f: 4 },
    { n: 'Guisantes secos', g: 90, kcal: 318, p: 22, c: 56, f: 1 },
    { n: 'Alubias negras', g: 180, kcal: 234, p: 16, c: 42, f: 1 },
  ],
  'Garbanzos cocidos': [
    { n: 'Lentejas cocidas', g: 200, kcal: 232, p: 18, c: 40, f: 1 },
    { n: 'Alubias blancas', g: 200, kcal: 236, p: 16, c: 42, f: 1 },
    { n: 'Habas cocidas', g: 200, kcal: 180, p: 14, c: 30, f: 1 },
    { n: 'Edamame', g: 160, kcal: 194, p: 18, c: 14, f: 8 },
  ],
  'Edamame': [
    { n: 'Garbanzos cocidos', g: 160, kcal: 197, p: 14, c: 32, f: 3 },
    { n: 'Guisantes', g: 200, kcal: 160, p: 10, c: 28, f: 1 },
    { n: 'Habas cocidas', g: 180, kcal: 162, p: 13, c: 27, f: 1 },
    { n: 'Alubias negras', g: 140, kcal: 182, p: 12, c: 32, f: 1 },
  ],
  'Huevo': [
    { n: 'Tofu scramble', g: 150, kcal: 145, p: 18, c: 3, f: 7 },
    { n: 'Clara de huevo', g: 180, kcal: 94, p: 20, c: 1, f: 0 },
    { n: 'Proteína vegetal en polvo', g: 30, kcal: 120, p: 22, c: 4, f: 2 },
    { n: 'Lentejas cocidas', g: 120, kcal: 139, p: 11, c: 24, f: 1 },
  ],
  'Proteína vegetal en polvo': [
    { n: 'Quark desnatado', g: 200, kcal: 134, p: 24, c: 8, f: 0 },
    { n: 'Skyr natural', g: 200, kcal: 128, p: 22, c: 8, f: 0 },
    { n: 'Clara de huevo', g: 200, kcal: 104, p: 22, c: 1, f: 0 },
    { n: 'Proteína de soja texturizada', g: 30, kcal: 96, p: 15, c: 6, f: 1 },
  ],
  // Lácteos y fermentados
  'Quark desnatado': [
    { n: 'Yogur griego 0%', g: 150, kcal: 88, p: 15, c: 6, f: 0 },
    { n: 'Skyr', g: 150, kcal: 96, p: 17, c: 6, f: 0 },
    { n: 'Requesón', g: 150, kcal: 147, p: 17, c: 5, f: 7 },
    { n: 'Cottage cheese', g: 150, kcal: 129, p: 18, c: 5, f: 4 },
  ],
  'Yogur griego 0%': [
    { n: 'Quark desnatado', g: 150, kcal: 100, p: 18, c: 6, f: 0 },
    { n: 'Skyr', g: 150, kcal: 96, p: 17, c: 6, f: 0 },
    { n: 'Requesón', g: 150, kcal: 147, p: 17, c: 5, f: 7 },
    { n: 'Kéfir natural', g: 150, kcal: 90, p: 8, c: 10, f: 2 },
  ],
  'Skyr': [
    { n: 'Quark desnatado', g: 150, kcal: 100, p: 18, c: 6, f: 0 },
    { n: 'Yogur griego 0%', g: 150, kcal: 88, p: 15, c: 6, f: 0 },
    { n: 'Cottage cheese', g: 150, kcal: 129, p: 18, c: 5, f: 4 },
    { n: 'Requesón', g: 150, kcal: 147, p: 17, c: 5, f: 7 },
  ],
  'Leche de avena': [
    { n: 'Leche de almendras', g: 80, kcal: 29, p: 1, c: 4, f: 1 },
    { n: 'Leche de soja', g: 80, kcal: 34, p: 3, c: 3, f: 1 },
    { n: 'Leche de coco light', g: 80, kcal: 64, p: 1, c: 2, f: 6 },
    { n: 'Bebida de arroz', g: 80, kcal: 43, p: 0, c: 9, f: 1 },
  ],
  'Leche de coco light': [
    { n: 'Nata de coco', g: 60, kcal: 120, p: 1, c: 2, f: 12 },
    { n: 'Leche de soja', g: 100, kcal: 43, p: 4, c: 4, f: 2 },
    { n: 'Yogur de coco', g: 80, kcal: 96, p: 1, c: 4, f: 9 },
    { n: 'Crema de cacahuete diluida', g: 20, kcal: 118, p: 5, c: 3, f: 10 },
  ],
  // Frutas
  'Arándanos': [
    { n: 'Frutos rojos mixtos', g: 80, kcal: 36, p: 1, c: 8, f: 0 },
    { n: 'Frambuesas', g: 90, kcal: 47, p: 1, c: 11, f: 0 },
    { n: 'Cerezas sin hueso', g: 80, kcal: 51, p: 1, c: 12, f: 0 },
    { n: 'Mango en dados', g: 80, kcal: 51, p: 1, c: 13, f: 0 },
  ],
  'Frutos rojos': [
    { n: 'Arándanos', g: 80, kcal: 46, p: 1, c: 11, f: 0 },
    { n: 'Frambuesas', g: 90, kcal: 47, p: 1, c: 11, f: 0 },
    { n: 'Fresas', g: 100, kcal: 32, p: 1, c: 8, f: 0 },
    { n: 'Moras', g: 80, kcal: 43, p: 1, c: 10, f: 0 },
  ],
  'Frutos rojos congelados': [
    { n: 'Mango congelado', g: 130, kcal: 83, p: 1, c: 20, f: 0 },
    { n: 'Frambuesas congeladas', g: 130, kcal: 68, p: 2, c: 15, f: 1 },
    { n: 'Cereza congelada', g: 130, kcal: 84, p: 1, c: 20, f: 0 },
    { n: 'Piña congelada', g: 130, kcal: 67, p: 1, c: 16, f: 0 },
  ],
  'Plátano': [
    { n: 'Mango', g: 110, kcal: 70, p: 1, c: 17, f: 0 },
    { n: 'Pera madura', g: 130, kcal: 72, p: 0, c: 17, f: 0 },
    { n: 'Caqui', g: 100, kcal: 70, p: 1, c: 18, f: 0 },
    { n: 'Uvas', g: 120, kcal: 83, p: 1, c: 22, f: 0 },
  ],
  'Manzana': [
    { n: 'Pera', g: 180, kcal: 99, p: 1, c: 25, f: 0 },
    { n: 'Melocotón', g: 200, kcal: 96, p: 2, c: 23, f: 0 },
    { n: 'Naranja', g: 200, kcal: 94, p: 2, c: 22, f: 0 },
    { n: 'Plátano pequeño', g: 100, kcal: 89, p: 1, c: 23, f: 0 },
  ],
  // Frutos secos y semillas
  'Nueces': [
    { n: 'Almendras', g: 15, kcal: 87, p: 3, c: 2, f: 8 },
    { n: 'Anacardos', g: 15, kcal: 87, p: 3, c: 5, f: 7 },
    { n: 'Semillas de girasol', g: 15, kcal: 89, p: 3, c: 3, f: 8 },
    { n: 'Semillas de calabaza', g: 14, kcal: 79, p: 4, c: 2, f: 7 },
  ],
  'Semillas de girasol': [
    { n: 'Nueces', g: 14, kcal: 91, p: 2, c: 2, f: 9 },
    { n: 'Semillas de calabaza', g: 14, kcal: 79, p: 4, c: 2, f: 7 },
    { n: 'Almendras laminadas', g: 14, kcal: 81, p: 3, c: 2, f: 7 },
    { n: 'Semillas de chía', g: 10, kcal: 49, p: 2, c: 4, f: 3 },
  ],
  'Semillas de chía': [
    { n: 'Semillas de lino molido', g: 10, kcal: 54, p: 2, c: 3, f: 4 },
    { n: 'Semillas de girasol', g: 12, kcal: 71, p: 2, c: 2, f: 6 },
    { n: 'Semillas de cáñamo', g: 10, kcal: 55, p: 3, c: 1, f: 5 },
    { n: 'Nueces picadas', g: 12, kcal: 78, p: 2, c: 1, f: 8 },
  ],
  'Granola sin azúcar': [
    { n: 'Muesli sin azúcar', g: 40, kcal: 152, p: 4, c: 26, f: 4 },
    { n: 'Copos de avena tostados', g: 40, kcal: 156, p: 5, c: 27, f: 3 },
    { n: 'Mezcla de semillas y frutos secos', g: 30, kcal: 162, p: 5, c: 6, f: 14 },
    { n: 'Granola de proteína', g: 35, kcal: 155, p: 7, c: 22, f: 4 },
  ],
  // Grasas saludables
  'Aguacate': [
    { n: 'Hummus', g: 90, kcal: 175, p: 8, c: 16, f: 9 },
    { n: 'Tahini', g: 30, kcal: 180, p: 5, c: 5, f: 16 },
    { n: 'Crema de almendras', g: 22, kcal: 134, p: 4, c: 4, f: 12 },
    { n: 'Aceite de oliva + limón', g: 15, kcal: 132, p: 0, c: 0, f: 15 },
  ],
  'Tahini': [
    { n: 'Crema de almendras', g: 30, kcal: 183, p: 6, c: 6, f: 16 },
    { n: 'Crema de anacardos', g: 30, kcal: 174, p: 5, c: 9, f: 14 },
    { n: 'Mantequilla de cacahuete', g: 28, kcal: 168, p: 7, c: 6, f: 14 },
    { n: 'Aguacate', g: 60, kcal: 96, p: 1, c: 4, f: 9 },
  ],
  'Crema de almendras': [
    { n: 'Mantequilla de cacahuete', g: 20, kcal: 120, p: 5, c: 4, f: 10 },
    { n: 'Tahini', g: 20, kcal: 120, p: 3, c: 3, f: 11 },
    { n: 'Crema de anacardos', g: 20, kcal: 116, p: 3, c: 6, f: 9 },
    { n: 'Crema de avellanas sin azúcar', g: 18, kcal: 113, p: 3, c: 4, f: 10 },
  ],
  'Hummus': [
    { n: 'Baba ganoush', g: 80, kcal: 104, p: 4, c: 12, f: 5 },
    { n: 'Guacamole', g: 80, kcal: 128, p: 2, c: 7, f: 11 },
    { n: 'Paté de lentejas', g: 80, kcal: 136, p: 8, c: 18, f: 4 },
    { n: 'Crema de alubias blancas', g: 80, kcal: 120, p: 7, c: 19, f: 2 },
  ],
  // Verduras
  'Brócoli': [
    { n: 'Coliflor', g: 120, kcal: 36, p: 3, c: 7, f: 0 },
    { n: 'Judías verdes', g: 130, kcal: 41, p: 3, c: 8, f: 0 },
    { n: 'Espárragos', g: 130, kcal: 30, p: 3, c: 6, f: 0 },
    { n: 'Col rizada (kale)', g: 100, kcal: 35, p: 3, c: 6, f: 0 },
  ],
  'Pimiento rojo': [
    { n: 'Tomate', g: 100, kcal: 18, p: 1, c: 4, f: 0 },
    { n: 'Calabacín', g: 120, kcal: 22, p: 2, c: 4, f: 0 },
    { n: 'Berenjena', g: 110, kcal: 26, p: 1, c: 5, f: 0 },
    { n: 'Zanahoria', g: 100, kcal: 41, p: 1, c: 10, f: 0 },
  ],
  'Espinacas frescas': [
    { n: 'Acelgas', g: 80, kcal: 17, p: 2, c: 3, f: 0 },
    { n: 'Rúcula', g: 60, kcal: 15, p: 2, c: 2, f: 0 },
    { n: 'Col rizada (kale)', g: 70, kcal: 25, p: 2, c: 4, f: 0 },
    { n: 'Canónigos', g: 60, kcal: 12, p: 1, c: 2, f: 0 },
  ],
  'Espinacas': [
    { n: 'Acelgas', g: 60, kcal: 13, p: 1, c: 2, f: 0 },
    { n: 'Rúcula', g: 60, kcal: 15, p: 2, c: 2, f: 0 },
    { n: 'Col rizada (kale)', g: 60, kcal: 21, p: 2, c: 3, f: 0 },
    { n: 'Canónigos', g: 60, kcal: 12, p: 1, c: 2, f: 0 },
  ],
  'Calabaza': [
    { n: 'Boniato', g: 220, kcal: 189, p: 3, c: 44, f: 0 },
    { n: 'Zanahoria', g: 300, kcal: 123, p: 3, c: 29, f: 0 },
    { n: 'Chirivía', g: 250, kcal: 175, p: 4, c: 43, f: 1 },
    { n: 'Nabo', g: 350, kcal: 98, p: 3, c: 23, f: 0 },
  ],
  'Zanahoria': [
    { n: 'Pimiento rojo', g: 100, kcal: 31, p: 1, c: 6, f: 0 },
    { n: 'Pepino', g: 120, kcal: 19, p: 1, c: 4, f: 0 },
    { n: 'Apio', g: 120, kcal: 20, p: 1, c: 4, f: 0 },
    { n: 'Rábano', g: 100, kcal: 16, p: 1, c: 3, f: 0 },
  ],
  'Tomate triturado': [
    { n: 'Puré de tomate casero', g: 100, kcal: 29, p: 1, c: 6, f: 0 },
    { n: 'Tomate cherry entero', g: 120, kcal: 22, p: 1, c: 5, f: 0 },
    { n: 'Passata de tomate', g: 100, kcal: 32, p: 2, c: 6, f: 0 },
    { n: 'Pimiento y tomate sofrito', g: 100, kcal: 55, p: 1, c: 8, f: 2 },
  ],
  // Otros
  'Salsa de soja': [
    { n: 'Tamari sin gluten', g: 10, kcal: 6, p: 1, c: 1, f: 0 },
    { n: 'Aminoácidos de coco', g: 12, kcal: 10, p: 0, c: 2, f: 0 },
    { n: 'Salsa teriyaki ligera', g: 12, kcal: 18, p: 1, c: 4, f: 0 },
    { n: 'Miso blanco diluido', g: 15, kcal: 22, p: 1, c: 3, f: 0 },
  ],
  'Pesto de albahaca': [
    { n: 'Pesto de espinacas', g: 30, kcal: 108, p: 3, c: 2, f: 10 },
    { n: 'Pesto de rúcula y nueces', g: 30, kcal: 120, p: 3, c: 2, f: 12 },
    { n: 'Salsa de tomate y albahaca', g: 60, kcal: 50, p: 2, c: 7, f: 2 },
    { n: 'Tapenade de aceitunas', g: 25, kcal: 88, p: 1, c: 2, f: 9 },
  ],
};

export const WEEK_DAYS: WeekDay[] = [
  { d: 'Lun', n: 6, tag: 'Gimnasio · Fuerza', kcal: 2300, color: '#ff6a3d' },
  { d: 'Mar', n: 7, tag: 'Baloncesto 2h', kcal: 2520, color: '#ffb02e' },
  { d: 'Mié', n: 8, tag: 'Salsa · Baile', kcal: 2160, color: '#ef6f24' },
  { d: 'Jue', n: 9, tag: 'Cardio + Core', kcal: 2280, color: '#ffb02e' },
  { d: 'Vie', n: 10, tag: 'Descanso', kcal: 2000, color: '#9a9087' },
  { d: 'Sáb', n: 11, tag: 'Cardio pump', kcal: 2250, color: '#ff6a3d' },
  { d: 'Dom', n: 12, tag: 'Descanso activo', kcal: 2050, color: '#5fb37a' },
];

export const WEEK_MEALS: string[][] = [
  ['Porridge de espelta', 'Bowl de lentejas y arroz', 'Quark con nueces', 'Tofu con boniato'],
  ['Tostada de centeno y aguacate', 'Curry de garbanzos y arroz', 'Batido de proteína vegetal', 'Pasta de espelta con edamame'],
  ['Porridge de espelta con quark', 'Lentejas con arroz y pimiento', 'Quark con edamame', 'Tofu salteado con boniato'],
  ['Revuelto de huevo y centeno', 'Buddha bowl de quinoa', 'Yogur con frutos secos', 'Tortilla de verduras'],
  ['Gofre de avena', 'Ensalada de garbanzos', 'Hummus con crudités', 'Crema de calabaza con semillas'],
  ['Pancakes de quark', 'Chili sin carne con arroz', 'Frutos secos', 'Tofu teriyaki con espelta'],
  ['Bowl de yogur y granola', 'Quiche de verduras', 'Manzana y almendras', 'Sopa de lentejas'],
];

export const WEEK_MEAL_SLOTS = ['Desayuno', 'Almuerzo', 'Snack', 'Cena'];

